#!/usr/bin/env bash
# Display information about subdomains

print_subdomains() {
    local domain="$1"
    local subdomain="$2"

    # Define subdomains
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        # Use dig command to get DNS information
        result=$(dig +short "$sub.$domain" | awk '{print $1}')
        
        # Determine the record type and destination IP
        if [ -n "$result" ]; then
            record_type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }')
            destination=$(dig +short "$sub.$domain" | awk 'NR==1{print $1}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 2 ]; then
    print_subdomains "$1" "$2"
else [ "$#" -eq 1 ];
    print_subdomains "$1"
fi
