#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Strict host key checking must be disabled when using scp

# if less than 3 parameters passed
scp must transfer the file to the user home directory ~/

if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

file_path=$1
ip=$2
user_name=$3
ssh_key_path=$4

scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $user_name@$ip:~/
