#!/usr/bin/env bash
# Install Nginx on web server `web-01`

sudo apt-get -y update
sudo apt-get -y install nginx

# Adjust firewall to allow service
sudo ufw allow 'Nginx HTTP'

# Overwrite html file w/ "Hello World!" string
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
