#!/usr/bin/env bash
# Configure a new server

# Install Nginx on web server `web-01`
sudo apt-get -y update
sudo apt-get -y install nginx

# Adjust firewall to allow service
sudo ufw allow 'Nginx HTTP'

# Start Nginx
sudo service nginx start

# Overwrite html file w/ "Hello World!" string
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# 301 redirect page
redirect_301="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo sed -i "30i $redirect_301" /etc/nginx/sites-available/default

# 404 page with custome text
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

page_404="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /var/www/html;\n\t\tinternal;\n\t}\n"
style="#error_page 404 /404.html;"

sudo sed -i "s@$style@$page_404@" /etc/nginx/sites-available/default

# Start Nginx again to apply the changes
sudo service nginx restart
