#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
# header (on web-01 and web-02)

custom_header=add_header X-Served-By $hostname;
sudo sed -i "24i $custom_header" /etc/nginx/sites-available/default

sudo service nginx restart
