#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install haproxy

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

#  handle frontend config
sudo sed -i "\$a frontend myfrontend\n\tbind *:80\n\tdefault_backend mybackend" /etc/haproxy/haproxy.cfg

# use sed cmd to write server configurations into /etc/haproxy/haproxy.cfg
sudo sed -i "\$a backend mybackend\n\tbalance roundrobin\n\tserver web-01 204.236.241.48:80 check\n\tserver web-02 3.90.83.137:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
sleep 2  # Wait fo HAProxy to full start
