#!/usr/bin/env bash
#Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

terminate_script()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 1
}
# run terminate_script if SIGTERM is received

interrupt_script()
{
	echo "Y U no love me?!"
	exit 1
}
# run above funct if SIGINT is received

quit_script()
{
	rm /var/run/myscript.pid
	exit 1
}
# run above funct if SIGQUIT is received

# signal handlers below
trap "terminate_script" SIGTERM
trap "interrupt_script" SIGINT
trap "quit_script" SIGQUIT

touch /var/run/myscript.pid
echo "$$" >> myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
