#!/usr/bin/env bash
# Write a Bash script that displays:

# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

terminate_script()
{
	echo "I am invincible!!!"
}

# Set trap call to terminate_script funct when SIGTERM is received
trap "terminate_script" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
