#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

if [ -e "./school" ]; then
	echo "school file exists"
	if test -s "./school"; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if `school is a regular file
	if [ -f "./school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
