#!/usr/bin/env bash
# changes ip address of localhost and facebook

cp /etc/hosts hosts.old
cp /etc/hosts ~/hosts.new
sed -i '1s/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '$a\8.8.8.8\t\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
