#!/usr/bin/env bash
# Run cmds as another user

if [[ $# -eq 0 ]]; then
        whoami
elif [[ $# -eq 1 ]]; then
        sudo -u $1 whoami
else
        echo "Too many args passed"
        echo "Usage: <script> <arg>"
fi
