#!/usr/bin/env bash
# Configure nginx to run as non root user

# start nginx as non root user
# grant permission to file /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

# listen on port 8080
nginx_conf="/etc/nginx/sites-enabled/default"
sed -i "22c \\\tlisten *:8080;" "$nginx_conf"
sed -i "23c \\\tlisten [::]:8080;" "$nginx_conf"
