#!/usr/bin/env bash
# Configure nginx to run as non root user

# install nginx if not present
sudo apt-get update
sudo apt-get install -y nginx

# Create non root user = nginx
useradd nginx

# listen on port 8080
nginx_conf="/etc/nginx/sites-enabled/default"
sed -i "22c\tlisten 8088 default_server;" "$nginx_conf"

# start nginx as non root user
sudo -u nginx service nginx start
