#!/usr/bin/env bash
# Configure nginx to run as non root user

# install nginx if not present
sudo apt-get update
sudo apt-get install -y nginx

# Create non root user = nginx
groupadd -r nginx
useradd nginx

# start nginx as non root user
sudo -u nginx service nginx start
