#!/usr/bin/env bash
# Configure nginx to run as non root user
sudo apt-get update
sudo apt-get install -y nginx
groupadd -r nginx
useradd nginx -r -g nginx -d /var/cache/nginx -s /sbin/nologin
sudo -u nginx service nginx start
